### ISSUE TITLE
[feature request] python 3.11 wheel

### ISSUE THREAD

**Issue by Dragon-Git** [MikePopoloski/pyslang#157]
Add Python 3.11 wheel to PyPI for Python 3.11 users to use this project.

**Comment by MikePopoloski** [comment]
I believe the next release will include it automatically, as the build tools involved have updated to add 3.11 as a target.

**Comment by Dragon-Git** [comment]
The latest release version 3.0.310 includes a Python 3.11 wheel, thank you.

**Comment by MikePopoloski** [comment]
Yeah, I realized I ran the dist too early, before I had picked up the version bump from the upstream slang repo. I'm re-running it now so that the pyslang version properly gets bumped to 4.0
