### ISSUE TITLE
any more example for usage?

### ISSUE THREAD

**Issue by chenfeiyue123** [MikePopoloski/pyslang#183]
I attemp to call the functions  in class, but it seems like not work and always report usage error. can show more examples about usage?

**Comment by chenfeiyue123** [comment]
or give a list about functions which is ready for using

**Comment by MikePopoloski** [comment]
I don't have the resources to provide additional Python examples or documentation at this time. You can see the list of exposed functions for the Python bindings here: https://github.com/MikePopoloski/slang/tree/master/bindings/python

**Comment by MikePopoloski** [comment]
If you run into specific bugs with the bindings I'm happy to fix them of course. Feel free to open other issues if so.
