### ISSUE TITLE
visit default print 

### ISSUE THREAD

**Issue by a-bian** [MikePopoloski/pyslang#208]
The pyslang now has a new 'visit' method, but it seems that replacement is not supported yet.

Is there a similar way to implement the following?
```
rep = {"CEN":"PEN", "DEN":"KEN"}
def visit_sub(obj):
    if obj.kind.name in ["NamedPortConnection"]:
        if str(obj.name) in rep:
            print(".%s (%s)," % (rep[str(obj.name)],obj.expr))
        else:
            print ... # default print
    else:
        print ...  # default print

top.visit(visit_sub)
```
However, when using the above approach, Python 3 crashes directly.

Thanks

**Comment by MikePopoloski** [comment]
Do you have a full reproducer for the crash? Otherwise I'm not sure exactly what you're asking for.

**Comment by a-bian** [comment]
The issue has been resolved through other means, thank you!
