### ISSUE TITLE
Syntax tree from multiple files?

### ISSUE THREAD

**Issue by pistoletpierre** [MikePopoloski/pyslang#3]
Hi @MikePopoloski, thank you for putting this together. I was playing around with it today and am excited by the possibilities it holds.

One thing I was not able to do in the time I spent today is read in multiple files with which to create a SyntaxTree. Is there a way to do that currently?

**Comment by MikePopoloski** [comment]
It's possible in the C++ code via SyntaxTree::fromBuffers but that's not exposed to pyslang right now. I'll add that to the TODO list.

**Comment by MikePopoloski** [comment]
This has been added.
