### ISSUE TITLE
Python API Docs/Examples for source text

### ISSUE THREAD

**Issue by markNZed** [MikePopoloski/pyslang#358]
Hi, I'm trying to get the source location for each node in the AST and its associated string. I guess I am not using the library the way I should. Another option would be to use slang with JSON output.

I can get the source location with:

```
            source_range = node.sourceRange
            begin_line = self.source_manager.getLineNumber(source_range.start)
            begin_col = self.source_manager.getColumnNumber(source_range.start)
            start_loc = {
                'line': begin_line,
                'column': begin_col
            }
            end_line = self.source_manager.getLineNumber(source_range.end)
            end_col = self.source_manager.getColumnNumber(source_range.end)
            end_loc = {
                'line': end_line,
                'column': end_col
            }
            file_name = self.source_manager.getFileName(source_range.start)
```

Could someone please suggest the "right" way to get the source text associated with the node ? Thx

**Comment by MikePopoloski** [comment]
If you have a SourceLocation `loc` that represents a file location, you can use `sourceManager.getSourceText(loc.buffer)` to get the full texts of the file and then use `loc.offset` to jump to the character offset within that string.

The DiagnosticClient.cpp and TextDiagnosticClient.cpp files in the slang source do a fair amount of manipulation like this to print diagnostics; you can use that for inspiration if you know how to read C++.
