### ISSUE TITLE
Is there any documents to show how can I use it with Python

### ISSUE THREAD

**Issue by fzwwj95** [MikePopoloski/pyslang#57]
where can I know the function or class in pyslang？

**Comment by MikePopoloski** [comment]
Right now there is not separate documentation for pyslang. The most straightforward way to see what is possible is to look at the bindings here: https://github.com/MikePopoloski/slang/tree/master/bindings/python and to also look at the C++ reference documentation here: https://sv-lang.com/api-reference.html

At some point I'd like to automatically pull the C++ documentation and have it apply to the Python API but that's a project I haven't had time to do.
